server:
  port: 8888
  


spring:
  application:
    name: SHOP-EAZY-CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mapoulo/ShopEazyCloudConfig.git
          default-label: main
          clone-on-start: true    